version: '3.8'
services:
  thebidouilleur:
    # docker buildx build --platform=linux/amd64,linux/arm64 -t registry.thebidouilleur.xyz/thebidouilleur:latest . --push
    build:
        context: .
        dockerfile: Dockerfile
    image: ferrarijose/docusaurus:v1
    container_name: Hinsch
    ports:
      - 8080:80
